# Generated by Django 5.0.6 on 2024-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
